### ISSUE TITLE
Wth gihtub workflo taks fails?!1?1!1!1!

### ISSUE THREAD

**Issue by Snoworange420** [Snoworange420/Cranberry#4]
![4A977AB0-BA92-4508-B9AD-DFB7D82A4BEF](https://user-images.githubusercontent.com/110935731/222136473-69e19a8a-f332-4a67-a85f-8511e4525464.png)

**Comment by mostwise** [comment]
mayb dont mess with the code in it (aka changing the os it runs on)

**Comment by Snoworange420** [comment]
idk what the issue is bruh
