### ISSUE TITLE
Auto32k sucks

### ISSUE THREAD

**Issue by Snoworange420** [Snoworange420/Cranberry#5]
it takes like 300ms to complete and doesn't place vertically

**Comment by Snoworange420** [comment]
Doesnt place vertically tho

**Comment by violentqm** [comment]
Nigga need to fix it

**Comment by Snoworange420** [comment]
True

**Comment by Snoworange420** [comment]
it now places vertically and closing bug is fixed!!

**Comment by violentqm** [comment]
homosex
